-- ===========================================================
-- 高考分数时光机 · Supabase 建表 SQL
--
-- 在 Supabase 后台 → SQL Editor 粘贴执行。
-- 表名：box_records（与 js/config/supabase.js 中的 TABLE 一致）
-- ===========================================================

create table if not exists public.box_records (
  id            bigint generated by default as identity primary key,
  label_id      text        not null,         -- 标签 ID（如 chosen_one / blood_loss）
  label_name    text        not null,         -- 标签中文名（天选之子）
  tier          text        not null,         -- 稀有度：ssr/sr/r/n/hidden
  province      text        not null,         -- 省份代码（sc/ha/...）
  province_name text        not null,         -- 省份名（四川）
  exam_year     int         not null,         -- 用户当年高考年份
  score         int         not null,         -- 用户当年分数
  rank          int,                          -- 用户当年全省排名（V2 位次锚定）
  track         text,                         -- 科类：science/arts/physics/history/general
  track_label   text,                         -- 科类中文名（理科/物理类等）
  major         text,                         -- 专业名（仅展示，不参与判定）
  equivalent_score_2026 int,                  -- 2026 等位分（同位次换算结果）
  created_at    timestamptz not null default now()
);

-- 索引：按时间倒序查询（首页动态流 / 今日统计）
create index if not exists idx_box_records_created_at
  on public.box_records (created_at desc);

-- 索引：按省份统计
create index if not exists idx_box_records_province
  on public.box_records (province);

-- 索引：按标签统计（稀有度排行）
create index if not exists idx_box_records_label
  on public.box_records (label_id);

-- ===========================================================
-- RLS（行级安全）策略
-- 本表只允许匿名写入/读取（娱乐产品，无敏感信息）
-- ===========================================================

alter table public.box_records enable row level security;

-- 允许匿名插入
drop policy if exists "anon insert box_records" on public.box_records;
create policy "anon insert box_records"
  on public.box_records for insert
  to anon
  with check (true);

-- 允许匿名读取（排行榜需要）
drop policy if exists "anon select box_records" on public.box_records;
create policy "anon select box_records"
  on public.box_records for select
  to anon
  using (true);

-- ===========================================================
-- 验证：执行后可跑下面这句确认
-- select count(*) from public.box_records;
-- ===========================================================
